### ISSUE TITLE
Version 2.0 errors

### ISSUE THREAD

**Issue by northeaster** [FriendsOfFlarum/gamification#17]
```
Notice: Trying to get property 'id' of non-object in /var/www/sourceturk/flarum/vendor/fof/gamification/src/Listeners/AddRelationships.php on line 134

Notice: Trying to get property 'id' of non-object in /var/www/sourceturk/flarum/vendor/fof/gamification/src/Listeners/AddRelationships.php on line 134

Notice: Trying to get property 'id' of non-object in /var/www/sourceturk/flarum/vendor/fof/gamification/src/Listeners/AddRelationships.php on line 134

Notice: Trying to get property 'id' of non-object in /var/www/sourceturk/flarum/vendor/fof/gamification/src/Listeners/AddRelationships.php on line 134

Fatal error: Uncaught Laminas\HttpHandlerRunner\Exception\EmitterException: Output has been emitted previously; cannot emit response in /var/www/sourceturk/flarum/vendor/laminas/laminas-httphandlerrunner/src/Exception/EmitterException.php:24 Stack trace: #0 /var/www/sourceturk/flarum/vendor/laminas/laminas-httphandlerrunner/src/Emitter/SapiEmitterTrait.php(40): Laminas\HttpHandlerRunner\Exception\EmitterException::forOutputSent() #1 /var/www/sourceturk/flarum/vendor/laminas/laminas-httphandlerrunner/src/Emitter/SapiEmitter.php(27): Laminas\HttpHandlerRunner\Emitter\SapiEmitter->assertNoPreviousOutput() #2 /var/www/sourceturk/flarum/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(98): Laminas\HttpHandlerRunner\Emitter\SapiEmitter->emit() #3 /var/www/sourceturk/flarum/vendor/flarum/core/src/Http/Server.php(42): Laminas\HttpHandlerRunner\RequestHandlerRunner->run() #4 /var/www/sourceturk/flarum/public/index.php(26): Flarum\Http\Server->listen() #5 {main} thrown in /var/www/sourceturk/flarum/vendor/laminas/laminas-httphandlerrunner/src/Exception/EmitterException.php on line 24
```

**Comment by datitisev** [comment]
Fixed in 91a9987 (v0.2.1).
