### ISSUE TITLE
When I try to cancel an upvote or downvote, it returns a 404.

### ISSUE THREAD

**Issue by Pain4Din0** [FriendsOfFlarum/gamification#74]
## Bug Report

**Current Behavior**
When I try to cancel an upvote or downvote, it returns a 404. Click it another time will be fine.

**Steps to Reproduce**
1. Go to a page of my site like https://ncu.plus/d/6/
2. Click on upvote or downvote
3. Click it again to cancel the former action

**Expected Behavior**
The cancelation be performed immediately but not an error

**Environment**
- Flarum version: 1.2.1
- Extension version: 1.3.3
- Website URL: https://ncu.plus/
- Webserver: nginx
- Hosting environment: vps
- PHP version: 7.3.29
- Browser: Chrome and other browsers

**Logs**

<details><summary>Error log on the page</summary>

```
POST https://ncu.plus/api/posts/34

Illuminate\Database\Eloquent\ModelNotFoundException: No query results for model [FoF\Gamification\Vote]. in /www/wwwroot/ncu.plus/vendor/illuminate/database/Eloquent/Builder.php:527
Stack trace:
#0 /www/wwwroot/ncu.plus/vendor/illuminate/queue/SerializesAndRestoresModelIdentifiers.php(102): Illuminate\Database\Eloquent\Builder->firstOrFail()
#1 /www/wwwroot/ncu.plus/vendor/illuminate/queue/SerializesAndRestoresModelIdentifiers.php(57): FoF\Gamification\Jobs\VoteNotificationsJob->restoreModel(Object(Illuminate\Contracts\Database\ModelIdentifier))
#2 /www/wwwroot/ncu.plus/vendor/illuminate/queue/SerializesModels.php(45): FoF\Gamification\Jobs\VoteNotificationsJob->getRestoredPropertyValue(Object(Illuminate\Contracts\Database\ModelIdentifier))
#3 [internal function]: FoF\Gamification\Jobs\VoteNotificationsJob->__wakeup()
#4 /www/wwwroot/ncu.plus/vendor/illuminate/queue/CallQueuedHandler.php(97): unserialize('O:42:"FoF\\Gamif...')
#5 /www/wwwroot/ncu.plus/vendor/illuminate/queue/CallQueuedHandler.php(253): Illuminate\Queue\CallQueuedHandler->getCommand(Array)
#6 /www/wwwroot/ncu.plus/vendor/illuminate/queue/Jobs/Job.php(213): Illuminate\Queue\CallQueuedHandler->failed(Array, Object(Illuminate\Database\Eloquent\ModelNotFoundException), 'eba9c3aa-ddb2-4...')
#7 /www/wwwroot/ncu.plus/vendor/illuminate/queue/Jobs/Job.php(192): Illuminate\Queue\Jobs\Job->failed(Object(Illuminate\Database\Eloquent\ModelNotFoundException))
#8 /www/wwwroot/ncu.plus/vendor/illuminate/queue/CallQueuedHandler.php(238): Illuminate\Queue\Jobs\Job->fail(Object(Illuminate\Database\Eloquent\ModelNotFoundException))
#9 /www/wwwroot/ncu.plus/vendor/illuminate/queue/CallQueuedHandler.php(63): Illuminate\Queue\CallQueuedHandler->handleModelNotFound(Object(Illuminate\Queue\Jobs\SyncJob), Object(Illuminate\Database\Eloquent\ModelNotFoundException))
#10 /www/wwwroot/ncu.plus/vendor/illuminate/queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\SyncJob), Array)
#11 /www/wwwroot/ncu.plus/vendor/illuminate/queue/SyncQueue.php(43): Illuminate\Queue\Jobs\Job->fire()
#12 /www/wwwroot/ncu.plus/vendor/fof/gamification/src/Listeners/QueueJobs.php(28): Illuminate\Queue\SyncQueue->push(Object(FoF\Gamification\Jobs\VoteNotificationsJob))
#13 /www/wwwroot/ncu.plus/vendor/illuminate/events/Dispatcher.php(404): FoF\Gamification\Listeners\QueueJobs->notifications(Object(FoF\Gamification\Events\PostWasVoted))
#14 /www/wwwroot/ncu.plus/vendor/illuminate/events/Dispatcher.php(249): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('FoF\\Gamificatio...', Array)
#15 /www/wwwroot/ncu.plus/vendor/fof/gamification/src/Listeners/SaveVotesToDatabase.php(148): Illuminate\Events\Dispatcher->dispatch('FoF\\Gamificatio...')
#16 /www/wwwroot/ncu.plus/vendor/fof/gamification/src/Listeners/SaveVotesToDatabase.php(93): FoF\Gamification\Listeners\SaveVotesToDatabase->vote(Object(Flarum\Post\CommentPost), false, false, Object(Flarum\User\User), Object(Flarum\User\User))
#17 /www/wwwroot/ncu.plus/vendor/illuminate/events/Dispatcher.php(424): FoF\Gamification\Listeners\SaveVotesToDatabase->handle(Object(Flarum\Post\Event\Saving))
#18 /www/wwwroot/ncu.plus/vendor/illuminate/events/Dispatcher.php(249): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('Flarum\\Post\\Eve...', Array)
#19 /www/wwwroot/ncu.plus/vendor/flarum/core/src/Post/Command/EditPostHandler.php(79): Illuminate\Events\Dispatcher->dispatch('Flarum\\Post\\Eve...')
#20 /www/wwwroot/ncu.plus/vendor/illuminate/bus/Dispatcher.php(122): Flarum\Post\Command\EditPostHandler->handle(Object(Flarum\Post\Command\EditPost))
#21 /www/wwwroot/ncu.plus/vendor/illuminate/pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Flarum\Post\Command\EditPost))
#22 /www/wwwroot/ncu.plus/vendor/illuminate/pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Flarum\Post\Command\EditPost))
#23 /www/wwwroot/ncu.plus/vendor/illuminate/bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#24 /www/wwwroot/ncu.plus/vendor/illuminate/bus/Dispatcher.php(78): Illuminate\Bus\Dispatcher->dispatchNow(Object(Flarum\Post\Command\EditPost))
#25 /www/wwwroot/ncu.plus/vendor/flarum/core/src/Api/Controller/UpdatePostController.php(58): Illuminate\Bus\Dispatcher->dispatch(Object(Flarum\Post\Command\EditPost))
#26 /www/wwwroot/ncu.plus/vendor/flarum/core/src/Api/Controller/AbstractSerializeController.php(115): Flarum\Api\Controller\UpdatePostController->data(Object(Laminas\Diactoros\ServerRequest), Object(Tobscure\JsonApi\Document))
#27 /www/wwwroot/ncu.plus/vendor/flarum/core/src/Http/RouteHandlerFactory.php(41): Flarum\Api\Controller\AbstractSerializeController->handle(Object(Laminas\Diactoros\ServerRequest))
#28 /www/wwwroot/ncu.plus/vendor/flarum/core/src/Http/Middleware/ExecuteRoute.php(27): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}(Object(Laminas\Diactoros\ServerRequest), Array)
#29 /www/wwwroot/ncu.plus/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ExecuteRoute->process(Object(Laminas\Diactoros\ServerRequest), Object(Closure))
#30 /www/wwwroot/ncu.plus/vendor/flarum/core/src/Api/Middleware/ThrottleApi.php(33): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#31 /www/wwwroot/ncu.plus/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Api\Middleware\ThrottleApi->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#32 /www/wwwroot/ncu.plus/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(44): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#33 /www/wwwroot/ncu.plus/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\CheckCsrfToken->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#34 /www/wwwroot/ncu.plus/vendor/flarum/core/src/Http/Middleware/ResolveRoute.php(67): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#35 /www/wwwroot/ncu.plus/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ResolveRoute->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#36 /www/wwwroot/ncu.plus/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#37 /www/wwwroot/ncu.plus/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\SetLocale->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#38 /www/wwwroot/ncu.plus/vendor/flarum/core/src/Http/Middleware/AuthenticateWithHeader.php(58): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#39 /www/wwwroot/ncu.plus/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\AuthenticateWithHeader->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#40 /www/wwwroot/ncu.plus/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(31): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#41 /www/wwwroot/ncu.plus/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\AuthenticateWithSession->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#42 /www/wwwroot/ncu.plus/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(52): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#43 /www/wwwroot/ncu.plus/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\RememberFromCookie->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#44 /www/wwwroot/ncu.plus/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#45 /www/wwwroot/ncu.plus/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\StartSession->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#46 /www/wwwroot/ncu.plus/vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(29): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#47 /www/wwwroot/ncu.plus/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Api\Middleware\FakeHttpMethods->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#48 /www/wwwroot/ncu.plus/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#49 /www/wwwroot/ncu.plus/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ParseJsonBody->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#50 /www/wwwroot/ncu.plus/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#51 /www/wwwroot/ncu.plus/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\HandleErrors->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#52 /www/wwwroot/ncu.plus/vendor/flarum/core/src/Http/Middleware/InjectActorReference.php(25): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#53 /www/wwwroot/ncu.plus/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\InjectActorReference->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#54 /www/wwwroot/ncu.plus/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(76): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#55 /www/wwwroot/ncu.plus/vendor/middlewares/request-handler/src/RequestHandler.php(84): Laminas\Stratigility\MiddlewarePipe->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#56 /www/wwwroot/ncu.plus/vendor/laminas/laminas-stratigility/src/Next.php(51): Middlewares\RequestHandler->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#57 /www/wwwroot/ncu.plus/vendor/middlewares/base-path-router/src/BasePathRouter.php(101): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#58 /www/wwwroot/ncu.plus/vendor/laminas/laminas-stratigility/src/Next.php(51): Middlewares\BasePathRouter->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#59 /www/wwwroot/ncu.plus/vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php(36): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#60 /www/wwwroot/ncu.plus/vendor/laminas/laminas-stratigility/src/Next.php(51): Laminas\Stratigility\Middleware\OriginalMessages->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#61 /www/wwwroot/ncu.plus/vendor/middlewares/base-path/src/BasePath.php(73): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#62 /www/wwwroot/ncu.plus/vendor/laminas/laminas-stratigility/src/Next.php(51): Middlewares\BasePath->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#63 /www/wwwroot/ncu.plus/vendor/flarum/core/src/Http/Middleware/ProcessIp.php(24): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#64 /www/wwwroot/ncu.plus/vendor/laminas/laminas-stratigility/src/Next.php(51): Flarum\Http\Middleware\ProcessIp->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#65 /www/wwwroot/ncu.plus/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(76): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#66 /www/wwwroot/ncu.plus/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(65): Laminas\Stratigility\MiddlewarePipe->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\EmptyPipelineHandler))
#67 /www/wwwroot/ncu.plus/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(96): Laminas\Stratigility\MiddlewarePipe->handle(Object(Laminas\Diactoros\ServerRequest))
#68 /www/wwwroot/ncu.plus/vendor/flarum/core/src/Http/Server.php(44): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#69 /www/wwwroot/ncu.plus/public/index.php(26): Flarum\Http\Server->listen()
#70 {main}
```

</details>

<details><summary>Error log in the browser console</summary>

```
request.jss:173          POST https://ncu.plus/api/posts/34 404
（匿名） @ request.jss:173
（匿名） @ request.jss:23
（匿名） @ request.jss:22
e.request @ Application.tsxx:480
e.save @ Model.tss:220
Z @ saveVote.jss:23
u @ addVoteButtons.jss:46
onclick @ addVoteButtons.jss:56
L.handleEvent @ render.jss:888
Application.tsxx:548 POST https://ncu.plus/api/posts/34 404
Application.tsxx:551 Illuminate\Database\Eloquent\ModelNotFoundException: No query results for model [FoF\Gamification\Vote]. in /www/wwwroot/ncu.plus/vendor/illuminate/database/Eloquent/Builder.php:527
Stack trace:
#0 /www/wwwroot/ncu.plus/vendor/illuminate/queue/SerializesAndRestoresModelIdentifiers.php(102): Illuminate\Database\Eloquent\Builder->firstOrFail()
#1 /www/wwwroot/ncu.plus/vendor/illuminate/queue/SerializesAndRestoresModelIdentifiers.php(57): FoF\Gamification\Jobs\VoteNotificationsJob->restoreModel(Object(Illuminate\Contracts\Database\ModelIdentifier))
#2 /www/wwwroot/ncu.plus/vendor/illuminate/queue/SerializesModels.php(45): FoF\Gamification\Jobs\VoteNotificationsJob->getRestoredPropertyValue(Object(Illuminate\Contracts\Database\ModelIdentifier))
#3 [internal function]: FoF\Gamification\Jobs\VoteNotificationsJob->__wakeup()
#4 /www/wwwroot/ncu.plus/vendor/illuminate/queue/CallQueuedHandler.php(97): unserialize('O:42:"FoF\\Gamif...')
#5 /www/wwwroot/ncu.plus/vendor/illuminate/queue/CallQueuedHandler.php(253): Illuminate\Queue\CallQueuedHandler->getCommand(Array)
#6 /www/wwwroot/ncu.plus/vendor/illuminate/queue/Jobs/Job.php(213): Illuminate\Queue\CallQueuedHandler->failed(Array, Object(Illuminate\Database\Eloquent\ModelNotFoundException), 'eba9c3aa-ddb2-4...')
#7 /www/wwwroot/ncu.plus/vendor/illuminate/queue/Jobs/Job.php(192): Illuminate\Queue\Jobs\Job->failed(Object(Illuminate\Database\Eloquent\ModelNotFoundException))
#8 /www/wwwroot/ncu.plus/vendor/illuminate/queue/CallQueuedHandler.php(238): Illuminate\Queue\Jobs\Job->fail(Object(Illuminate\Database\Eloquent\ModelNotFoundException))
#9 /www/wwwroot/ncu.plus/vendor/illuminate/queue/CallQueuedHandler.php(63): Illuminate\Queue\CallQueuedHandler->handleModelNotFound(Object(Illuminate\Queue\Jobs\SyncJob), Object(Illuminate\Database\Eloquent\ModelNotFoundException))
#10 /www/wwwroot/ncu.plus/vendor/illuminate/queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\SyncJob), Array)
#11 /www/wwwroot/ncu.plus/vendor/illuminate/queue/SyncQueue.php(43): Illuminate\Queue\Jobs\Job->fire()
#12 /www/wwwroot/ncu.plus/vendor/fof/gamification/src/Listeners/QueueJobs.php(28): Illuminate\Queue\SyncQueue->push(Object(FoF\Gamification\Jobs\VoteNotificationsJob))
#13 /www/wwwroot/ncu.plus/vendor/illuminate/events/Dispatcher.php(404): FoF\Gamification\Listeners\QueueJobs->notifications(Object(FoF\Gamification\Events\PostWasVoted))
#14 /www/wwwroot/ncu.plus/vendor/illuminate/events/Dispatcher.php(249): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('FoF\\Gamificatio...', Array)
#15 /www/wwwroot/ncu.plus/vendor/fof/gamification/src/Listeners/SaveVotesToDatabase.php(148): Illuminate\Events\Dispatcher->dispatch('FoF\\Gamificatio...')
#16 /www/wwwroot/ncu.plus/vendor/fof/gamification/src/Listeners/SaveVotesToDatabase.php(93): FoF\Gamification\Listeners\SaveVotesToDatabase->vote(Object(Flarum\Post\CommentPost), false, false, Object(Flarum\User\User), Object(Flarum\User\User))
#17 /www/wwwroot/ncu.plus/vendor/illuminate/events/Dispatcher.php(424): FoF\Gamification\Listeners\SaveVotesToDatabase->handle(Object(Flarum\Post\Event\Saving))
#18 /www/wwwroot/ncu.plus/vendor/illuminate/events/Dispatcher.php(249): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('Flarum\\Post\\Eve...', Array)
#19 /www/wwwroot/ncu.plus/vendor/flarum/core/src/Post/Command/EditPostHandler.php(79): Illuminate\Events\Dispatcher->dispatch('Flarum\\Post\\Eve...')
#20 /www/wwwroot/ncu.plus/vendor/illuminate/bus/Dispatcher.php(122): Flarum\Post\Command\EditPostHandler->handle(Object(Flarum\Post\Command\EditPost))
#21 /www/wwwroot/ncu.plus/vendor/illuminate/pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Flarum\Post\Command\EditPost))
#22 /www/wwwroot/ncu.plus/vendor/illuminate/pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Flarum\Post\Command\EditPost))
#23 /www/wwwroot/ncu.plus/vendor/illuminate/bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#24 /www/wwwroot/ncu.plus/vendor/illuminate/bus/Dispatcher.php(78): Illuminate\Bus\Dispatcher->dispatchNow(Object(Flarum\Post\Command\EditPost))
#25 /www/wwwroot/ncu.plus/vendor/flarum/core/src/Api/Controller/UpdatePostController.php(58): Illuminate\Bus\Dispatcher->dispatch(Object(Flarum\Post\Command\EditPost))
#26 /www/wwwroot/ncu.plus/vendor/flarum/core/src/Api/Controller/AbstractSerializeController.php(115): Flarum\Api\Controller\UpdatePostController->data(Object(Laminas\Diactoros\ServerRequest), Object(Tobscure\JsonApi\Document))
#27 /www/wwwroot/ncu.plus/vendor/flarum/core/src/Http/RouteHandlerFactory.php(41): Flarum\Api\Controller\AbstractSerializeController->handle(Object(Laminas\Diactoros\ServerRequest))
#28 /www/wwwroot/ncu.plus/vendor/flarum/core/src/Http/Middleware/ExecuteRoute.php(27): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}(Object(Laminas\Diactoros\ServerRequest), Array)
#29 /www/wwwroot/
e.requestErrorDefaultHandler @ Application.tsxx:551
e.requestErrorCatch @ Application.tsxx:536
（匿名） @ Application.tsxx:480
Promise.catch（异步）
e.request @ Application.tsxx:480
e.save @ Model.tss:220
Z @ saveVote.jss:23
u @ addVoteButtons.jss:46
onclick @ addVoteButtons.jss:56
L.handleEvent @ render.jss:888
```

</details>

<details><summary>PHP Flarum info</summary>

```
PHP Warning:  PHP Startup: fileinfo: Unable to initialize module
Module compiled with module API=20170718
PHP    compiled with module API=20180731
These options need to match
 in Unknown on line 0
PHP Warning:  PHP Startup: redis: Unable to initialize module
Module compiled with module API=20170718
PHP    compiled with module API=20180731
These options need to match
 in Unknown on line 0
Flarum core 1.2.1
PHP version: 7.3.29
MySQL version: 5.6.50-log
Loaded extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, ctype, curl, dom, filter, ftp, gd, gettext, hash, iconv, intl, json, mbstring, SPL, session, pcntl, standard, PDO, mysqlnd, pdo_sqlite, Phar, posix, Reflection, pdo_mysql, shmop, SimpleXML, soap, sockets, sodium, mysqli, sysvsem, tokenizer, xml, xmlreader, xmlrpc, xmlwriter
+---------------------------------+-------------+--------+
| Flarum Extensions               |             |        |
+---------------------------------+-------------+--------+
| ID                              | Version     | Commit |
+---------------------------------+-------------+--------+
| flarum-subscriptions            | v1.2.0      |        |
| flarum-tags                     | v1.2.0      |        |
| flarum-flags                    | v1.2.0      |        |
| flarum-markdown                 | v1.2.0      |        |
| fof-follow-tags                 | 1.1.1       |        |
| flarum-suspend                  | v1.2.0      |        |
| flarum-approval                 | v1.2.0      |        |
| zequeen-acgembed-remastered     | v1.1.2      |        |
| v17development-seo              | v1.8.0      |        |
| ralkage-hcaptcha                | 1.0.0       |        |
| pipecraft-id-slug               | v1.1.0      |        |
| nomiscz-auth-steam              | v1.0.1      |        |
| michaelbelgium-discussion-views | v7.1.2      |        |
| matteocontrini-imgur-upload     | v3.9.1      |        |
| ianm-follow-users               | 1.0.0       |        |
| ganuonglachanh-sonic            | 0.1.5       |        |
| fof-user-bio                    | 1.0.2       |        |
| fof-terms                       | 1.1.2       |        |
| fof-socialprofile               | 1.1.1       |        |
| fof-sitemap                     | 1.0.3       |        |
| fof-reactions                   | 1.0.4       |        |
| fof-pretty-mail                 | 1.0.1       |        |
| fof-polls                       | 1.0.5       |        |
| fof-oauth                       | 1.2.0       |        |
| fof-nightmode                   | 1.2.1       |        |
| fof-masquerade                  | 2.1.0       |        |
| fof-links                       | 1.0.3       |        |
| fof-linguist                    | 1.0.3       |        |
| fof-gamification                | 1.3.3       |        |
| fof-forum-statistics-widget     | 1.0.2       |        |
| fof-formatting                  | 1.0.2       |        |
| fof-cookie-consent              | 1.1.0       |        |
| fof-best-answer                 | 1.1.9       |        |
| fof-ban-ips                     | 1.0.2       |        |
| fof-analytics                   | 1.0.0       |        |
| flarum-sticky                   | v1.2.0      |        |
| flarum-statistics               | v1.2.0      |        |
| flarum-nicknames                | v1.2.0      |        |
| flarum-mentions                 | v1.2.0      |        |
| flarum-lock                     | v1.2.0      |        |
| flarum-lang-russian             | 1.2.0-p1    |        |
| flarum-lang-japanese            | v3.3.0      |        |
| flarum-lang-english             | v1.2.0      |        |
| flarum-lang-chinese-simplified  | v1.1.1.1220 |        |
| flarum-emoji                    | v1.2.0      |        |
| flarum-bbcode                   | v1.2.0      |        |
| clarkwinkelmann-emojionearea    | 1.0.0       |        |
| clarkwinkelmann-circle-groups   | 1.0.1       |        |
| clarkwinkelmann-author-change   | 1.0.2       |        |
+---------------------------------+-------------+--------+
Base URL: https://ncu.plus
Installation path: /www/wwwroot/ncu.plus
Queue driver: sync
Mail driver: mail
Debug mode: ON
```
</details>

**Additional Context**
I would like to know if this is caused by a conflict between another plugin and this one. I am a newcomer to Flarum and love your plugins! I hope to hear from you.
Please feel free to contact me if you need to provide any further logs.

**Comment by iamdarkle** [comment]
I get this same issue, I think it might be part of this here too (https://discuss.flarum.org/d/20671-friendsofflarum-gamification/608) @Pain4Din0 could you confirm if this also happens to you with the alternate voting layout in the discussions list? It definitely looks like something is going wrong and it seems to only affect new installations, quite weird...
